name: Apply
on:
  push:
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
